language: node_js

repo_token: LVAyMscP1dfCDS17Z3bhZ4UnHHvz2MST6

node_js:  

  - 0.10.35

services: 
  - redis

script: npm test


after_script: npm run cov

after_success: 
  "curl -L -l https://coveralls.io/repos/github/navyxie/access-token-api/badge.svg?branch=master"
